dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
    - libboost-test-dev
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  skip_cleanup: true
  git checkout master
  git merge develop
  git push --set-upstream origin master
  git checkout develop  
